trigger:
  - none

pool: 
  vmImage: 'ubuntu-latest'

jobs:
  - job: HelloWorld
    steps:
      - script: echo Hello, world!
      - script: 'echo Hello, this build name is: $(Build.DefinitionName)!'